### PR TITLE
rename 'ar_AR' locale to 'ar'

### PR DESCRIPTION
**Pull request by nphilipp**
Locale identifiers consist of a language tag plus an optional region
subtag, generic locale files use only the language tag.

### CODE REVIEW

**Comment by Jehan** [comment]
AR is indeed not a proper region from ISO 3166-1. Worse, this is an existing region and it corresponds to [Argentina](https://www.iso.org/obp/ui/#iso:code:3166:AR).

Nevertheless it would seem there is no proper region for [Modern Standard Arabic](https://en.wikipedia.org/wiki/Modern_Standard_Arabic) since it is an agreed norm language across several countries. Therefore I assume ar_AR is the accepted "wrong" code to designate this standard Arabic. I could even find this [doc from Facebook](https://developers.facebook.com/docs/internationalization) which says:

> There are two exceptions that do not follow the ISO standard: ar_AR and es_LA. We use these to denote umbrella locales for Arabic and Spanish.

But yeah I agree it actually does not make sense and goes against the standard. I guess changing to just "ar" could better suited.
I see in GIMP, this is "ar" only too (and in various other software), for instance.

**Comment by Jehan** [comment]
@achadwick I would accept this one, but I guess that's more something that you should decide.

**Comment by nphilipp** [comment]
Yeah, the convention I know (Linux/glibc) is to not use a territory/region identifier if there is no territory/region to specify—after all, it's the C library that needs to match up the set locale with the available message catalogs. I've never seen something like what Facebook does here before—and now I've seen it, I really could have done without, it's ugly ;), but it works for them because they do the matching on their side of things and can get away with all kinds of abuse there.

**Comment by Jehan** [comment]
Yes you are right. The locale "ar_AR" does not exist when I run `locale -a` and I guess creating it would be counter-productive. On the other hand, if I set any of the other "ar_*" locale to LC_ALL and run a program using just "ar" language, it will still fallback to this generic language. So it definitely makes sense. Let's just merge.

**Comment by achadwick** [comment]
I'm a bit late to the party here, but this looks fine to me. `ar_AR` is a duff code from a technical perspective, and we should use something else. Thanks for checking this.

I wish I knew a bit more about the content of that file. Specifically what variety of Arabic it really is. Does anyone know?

My uninformed take is that an `ar` code without a suffix primarily needs to be entirely MSA, or entirely some (pretty widely understood) local variety/dialect. Whatever it is, we should capture the 'lect(s) used in any given file in a human-readable comment if we can, to avoid errors of presentation.

"What facebook do" is probably fine for people using fb. Perhaps less good for i18n fallbacks on a desktop, where we have to be more careful.

I've as the most recent translator to have a look at this thread, as an extra check.

**Comment by Jehan** [comment]
Yes the "ar" only file should definitely be Modern Standard Arabic IMO as well.
Any other specific localized variant should have a region attached to "ar_".

**Pull request merged**
