### PR TITLE
Standardize libmypaint build for both GIMP and MyPaint - version 2

### PR DESCRIPTION
**Pull request by Jehan**
Since the pull request 31 won't update anymore after the revert, here is a new pull request. I fixed the tests when libmypaint is built as a shared lib (now the `nosetests` command finishes with value 0 when run from tree root).

### CODE REVIEW

**Comment by achadwick** [comment]
Travis is still breaking with it: <https://travis-ci.org/mypaint/libmypaint/builds/105957174>. Did you run `scons --clean` first before running nosetests? If I do that, I can reproduce the same breakage here.

However AppVeyor seems happier now than with pull #31: https://ci.appveyor.com/project/jonnor/libmypaint/build/1.0.115

**Comment by Jehan** [comment]
Funny, I would have expected the opposite since I only tested on Linux! :-)
In any case, I don't have the break, even when running `scons --clean` (I actually did more by making a full repository clean with `git clean -dfx`).

> same breakage here

This is not the same breakage when looking closer. Previously it could not find libmypaint-tests.so, and now libmypaint.so. Anyway I just updated my last commit. Could you test again? I think it should work now.

**Comment by achadwick** [comment]
Sorry, I meant "I get the same error that Travis saw: the changed on about libmypaint.so" ☺

**Comment by achadwick** [comment]
Extra cleanup stages may be needed. Manually, I'm doing a lot of

```
$ find . \( -iname '*.a' -o -iname '*.so' \) -exec rm -vf {} \;
```

right now :fearful: 

I note that nosetests runs just fine with this branch if you build with `use_sharedlib=False`. That skirts a lot of the problem of runtime linkage, and still allows us to test whether brushes paint stuff reasonably quickly (which is what matters). Leads me to think that:

```patch
diff --git a/.travis.yml b/.travis.yml
index 75ffc41..aab490c 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -10,5 +10,6 @@ addons:
       - python-nose
 
 script:
-    - scons
+    - scons use_sharedlib=false
     - nosetests
+    - scons use_sharedlib=true
```

might be sensible. I'm going to wave 34e5797 at Travis first, then see if patching like that does anything.

**Comment by achadwick** [comment]
That seems to be going better now. Thanks for the fixes! I'll test against mypaint too shortly.

One very good question that arises out of this: why is the static builder not being run for a shared build? And also, how can we get [`env.Program()`](http://www.scons.org/doc/production/HTML/scons-man.html#b-Program) to make a statically-linked binary for testing in the presence of both a `.a` and a `.so`?

**Comment by achadwick** [comment]
Relevant for the MyPaint build: mypaint/mypaint#542.

**Pull request merged**
