### PR TITLE
Standardize libmypaint build for both GIMP and MyPaint

### PR DESCRIPTION
**Pull request by Jehan**
This implements requests from issue #28.

- enable_gegl=true and use_sharedlibs=true are now the default.
- MyPaint-only environments can still disable gegl by building with enable_gegl=false.
- GIMP does not need introspection as of today. If it happens someday, we can still discuss to change the default value of enable_introspection later. :-)
Of course, if you prefer, we can also make it a default value to true. I don't think it is any problem for us.

### CODE REVIEW

**Comment by DanielSabo** [comment]
Just wanted to note that Gimp doesn't require building with enable_gegl=true any more.

**Comment by achadwick** [comment]
@DanielSabo Thanks. I wanted confirmation of that. So to make sure I'm certain what GIMP peeps are asking here: if the default configuration of a shared library with headers distro of libmypaint were enable_gegl=True, then that would be both supported by GIMP and (crucially) not worse for GIMP's mypaint brush tool?

**Comment by achadwick** [comment]
@Jehan if we're cetain about this, please can you remove `Sconstruct: enable_gegl=True is now the default. b6b8f2f` from this PR and do a forced push to its branch? Thanks.

**Comment by Jehan** [comment]
I'm pretty sure that I already said so in another of your tickets (about enable_gegl not being mandatory anymore), but anyway. :-)
And unless you do something other than just adding another API when enable_gegl is true, I don't see a reason why that would be worse for GIMP mypaint brush tool. In any case, I can confirm it works OK both when libmypaint is build or without the option.

@achadwick I will try remove the enable_gegl commit, but last time I tried a force push, I think that github forbad me from doing such thing.

**Comment by Jehan** [comment]
@achadwick Well actually force push did work. The commit to make enable_gegl a default has been removed.

**Comment by achadwick** [comment]
Thanks for the confirmations, everyone. Merging.

**Comment by achadwick** [comment]
Whoops, builds are failing now.

* <https://travis-ci.org/mypaint/libmypaint/builds/105915390>
* <https://ci.appveyor.com/project/jonnor/libmypaint>

Reverted and reopening until this PR fixes the build.

**Comment by Jehan** [comment]
Hi,

In your logs, I see it fails during "nosetests", which is apparently for unit test. How does this work to run these tests? If I try to run the `nosetests` command from the tree root, I get `Ran 0 tests in 0.008s […] OK`.

In any case, it fails with `error while loading shared libraries: libmypaint-tests.so`. But I really can't find a reference to what libmypaint-tests lib is (I assume with the name it is only for unit tests. But where is it built? Is it in the tree?).

**Comment by Jehan** [comment]
Oh ok, I rebuilt and I had such a lib. Apparently the libmypaint-tests.so is not built with the `install` target. Dismiss my previous message. :-)

**Comment by Jehan** [comment]
@achadwick: I fixed the unit testing on my branch (see my last commit) but it does not seem like the pull request updates itself. Should I open a new pull request?

**Comment by achadwick** [comment]
@Jehan I think that's probably right. Did you get AppVeyor working again? I updated the comment above to have a more direct link to the failed build.

(We should get AppVeyor using MSYS2 since that's scriptable in the nice way... #44)

**Comment by Jehan** [comment]
@achadwick not sure why you ask me if I had it work "again", since I don't think we ever discussed AppVeyor. Actually I didn't even know what this is until 2 min ago when I searched the web. :P 

For this issue, I simply reproduced the commands in your travis build. So I can say that on my machine, running `scons` followed by `nosetests` works well after my additional commit. I have not installed any continuous integration server on my machine.

Also I have opened the pull request #43 since this one seems to be closed.

**Comment by achadwick** [comment]
We only use AppVeyor as a third party service, hooked into GitHub for notification. Same deal as Travis, but more Windows-y ☺

I noticed that #31 was breaking *both* builds, 

* https://travis-ci.org/mypaint/libmypaint/builds/105915390
* https://ci.appveyor.com/project/jonnor/libmypaint/build/1.0.110

so I reverted. Silly me, I should have checked on a side branch first of course...  :stuck_out_tongue_closed_eyes:

**Pull request merged**
