### PR TITLE
Zoomfix

### PR DESCRIPTION
**Pull request by briend**
Significant improvement in existing brush appearance continuity.  I will still need to tweak some brushes but this seems to fix a lot of them.

### CODE REVIEW

**Comment by achadwick** [comment]
Thanks for attending to this - assume it's for mypaint/libmypaint#91 :smile:

Should I merge it straight away, or wait for the brush tweaks?

**Comment by briend** [comment]
I was thinking to merge this right away :-) and the MyPaint too so the tests don't fail.  Then I'll add a patch to MyPaint for just the brush.myb tweaks and we'll all be happy.  Thanks for handling the API breakage stuff!

**Comment by achadwick** [comment]
No problem. Just needed to refresh my memory of what version number goes where and why.

BTW, we've just done a major API bump, so other breaking changes can be merged. But maybe we want to do something so that future new parameters don't break stroke_to()?

There's no need to PR everything if the tests all pass and you think you've had all the scrutiny needed. Do you want to merge this (and mypaint/mypaint#822 straight after)?

**Comment by briend** [comment]
Done!  I do think it'd be great to avoid breaking stroke_to in the future.  There is potential for a lot more input devices, wheels, pens, etc.  Thanks @achadwick !

**Pull request merged**
