### PR TITLE
Anti offsets, direction_360, attack_angle, and offset tweaks [WIP]

### PR DESCRIPTION
**Pull request by briend**
This branch combines @anti-art's offset settings and direction_360 input since they turned out to be related quite a bit, and it simplified the code to combine them.  I created new settings to control the overall multiplier of the offsets, as well as the angle of the offsets (instead of just 90 degrees).  I also duplicated the offset side and offset mirrored, but instead of using Direction, they use Ascension.  This is surprisingly useful and less jittery, but requires a tilt pen.  Finally I included attack_angle (see [here](https://github.com/mypaint/libmypaint/pull/87) for previous discussion) input since it requires direction_360 and is a very small bit of code, as it is just the difference between ascension angle and the direction_360 angle.

Discussion should probably consolidate here:
https://github.com/mypaint/libmypaint/issues/8

### CODE REVIEW

**Comment by odysseywestra** [comment]
Okay @briend now that we are officially on 2.0-Devlopment, could you do you do a rebase and fix any potential conflicts?

**Comment by briend** [comment]
@odysseywestra rebased, seems to be ok.

**Comment by odysseywestra** [comment]
Could I get anyone from @mypaint/developers to review this pull request. If no one has any objections or concerns by Monday, I'm going to merge this PR. Oh, btw @briend you probably want to get some brushes made that take advantage of these features on MyPaint itself

**Comment by briend** [comment]
@odysseywestra good idea.  I wonder if a feature branch for a new brush group makes sense.  That way we can all collaborate on it for a while until it works for everyone, without a bunch of brushpack .zip files floating around. . .   Making nice icons for the brushes is probably the most difficult part for me, I should look for some free-to-use icons (any ideas?).  I would like a brush pack that has very expressive/dynsamic dip pens, fountain pens, pencils, charcoal, conte, stumps, bristle-brushes, etc.  This group could probably take advantage of the higher dabs-per-brush-radius, and require a bit more cpu than the other brushes.

**Comment by odysseywestra** [comment]
This would probably be a good time to ask @deevad to see if he would be interested in updating his brush pack to take advantage of these new parameters coming to libmypaint. I could probably help with the icons if you need some too.

**Comment by rbreu** [comment]
A new branch sounds great! I'd love to contribute/update my [bristle brushes](https://community.mypaint.org/t/brushset-rakes-bristles-uses-experimental-code/610), make a new demo painting, and maybe also make nicer icons, once we've finalised the brushes. I'm super busy atm, but I hope to have more time soon.

**Comment by briend** [comment]
@rbreu sound like a plan!  I created a branch here for us to start pushing brushes to:
https://github.com/mypaint/mypaint/tree/NewBrushes
@AnTi-ArT has a bunch of really great brushes too that might want to be updated and added to this branch.

**Comment by odysseywestra** [comment]
@rbreu this is planned on being merged in tomorrow, or so. If you can get a PR ready for your brushes for MyPaint git repo, that would be great. They don't have to be pretty. just functional. Afterwards, if you want to be able to edit the brush directly without PRs, I can open a new issue to have to you added to the developers team. Then you can add your icons and final touches to them without problems.

**Comment by odysseywestra** [comment]
Okay, I'm going to merge this in. @briend be prepared to fix any bugs that may arise.

**Pull request merged**
