### PR TITLE
Brush Input: 360deg Direction added

### PR DESCRIPTION
**Pull request by AnTi-ArT**
The default "Direction" only goes from 0 to 180. This new input allows a setting all the way around the circle, without repeat. e.g one can draw a full hue circle or draw curves that change only at the bottom.
The internal name is still direction_angle (like the old code), display name is renamed to "Direction 360" to be more clear, old brushes that used this should still work.

### CODE REVIEW

**Comment by AnTi-ArT** [comment]
[Longer description + images at the forum](https://community.mypaint.org/t/pull-requests-360deg-direction-offsets/425?u=anti)

**Comment by odysseywestra** [comment]
@achadwick is anything else need on this PR before we merge? @AnTi-ArT do you have anymore changes you would like to make before we merge this PR?

**Comment by odysseywestra** [comment]
@AnTi-ArT could you update your PR and look at the conflicts.

**Comment by briend** [comment]
The -gen.h files shouldn't be there right?  I forked @AnTi-ArT's branch as it is a prerequisite for another input- Attack Angle:
https://github.com/mypaint/libmypaint/pull/87
I tried to clean out the -gen.h files but maybe I shouldn't delete them?  I also applied the viewrotation calibration to direction_360 so it stays consistent when rotating the canvas.  So, maybe this PR is unnecessary.

**Comment by odysseywestra** [comment]
That would be an question for @achadwick or someone who is familiar with the brush engine. I would assume that @AnTi-ArT ran the py script and it generated the file which was committed in the end.

On that note we could probably close this one in favor of #87 , but lets get the `-gen.h` question answered first.

**Comment by briend** [comment]
Well, I know *-gen.h should be excluded because they are autogenerated and they are in the .gitignore file, but they seem to sneak in there somehow.  I tried to just rebase and remove them, but now I think my PR is deleting them from Master.  Which, I suppose should be fine but it makes the PR look scary :-)

**Comment by odysseywestra** [comment]
If it's in the .gitignore file then I would be okay with having the commit which deletes it. With that said:

Closing in favor of PR #87 
Continue Discussion on that Thread as well.

@briend could you update the Thread on our Community Forums so People will know where to find it?

**Comment by achadwick** [comment]
`mypaint-brush-settings-gen.h` and `brushsettings-gen.h` need to be present in the source distribution tarball alongside the generated `./configure` script. This is to remove the need for a Python interpreter from other people's build toolchains.

They're in git probably as a consequence of the old nasty SCons way of working.

In the new nasty autotools way of working, they can be generated by autogen.sh (which only maintainers and developers working from git ever need to run).

Now that we have a rather better Windows CI setup, I'm going to experiment with getting rid of them again. For the purposes of merging code, this means getting people to rebase against master and make sure that their forks don't accidentally reintroduce them.

**Pull request closed without merging**
