### PR TITLE
Input: Angle of attack

### PR DESCRIPTION
**Pull request by briend**
I was holding onto this patch because it relies on @Anti-Art's Direction360 and I didn't want redundant code out there, but I might as well get some feedback on this.  It can be pretty useful for emulating side-to-side effects or dab-ratio/angle effects that follow the brush even if you change the orientation of your pen.

This is distinctly different than direction, but the best name I can think for it is attack angle.  I used to play flight simulators as a kid so maybe there is a more sensible name someone can suggest.
screenshot 2017-06-09 23 24 46

### CODE REVIEW

**Comment by odysseywestra** [comment]
Okay so how do these three parameters(Direction, Direction 360, and Attack Angle) differ from each other? If the Direction parameters are basically the same with the exception of one being limited to 180 and the other 360, then I would suggest just combine the two with 360 being the default.

**Comment by briend** [comment]
@odysseywestra So, direction (180) and direction_360 are pretty similar and I *think* you could do anything with 360 that you can do with the 180.  There are surprisingly only ~3 default brushes that use direction, it seems, but obviously it would break stuff out there, and Direction (180) might be more intuitive to use for some effects.  

Attack Angle might be more useful for a few things-  BUT it requires a tilt-enabled stylus (I should add that to the description), which the others don't. Attack Angle lets you do things like "make the brush jitter or change somehow when I move it side-to-side but NOT when I push or pull it".  The important thing is that Attack Angle is totally consistent regardless of if you are left-handed, right-handed, or if you move your hand around to different positions as you draw. 

I just realized my screenshot above cuts off the degrees on the curve widget.  The middle is 0 and left and right extremes are -180 and +180.   So zero would mean the pen is going "forward" (same direction it is pointing its tip),  -90 the pen is "strafing/side-stepping" left (while "looking" forward), +90 the pen is "strafing/side-stepping" right and +180/-180 would be going backwards.

**Comment by odysseywestra** [comment]
So basically Attack Angle is an alternative to Declination and Ascension(which should be renamed to vertical and horizontal tilt but I'll leave that for another issue) by divine a starting point for the tilt functions? I'm still confused by how it all work, but I can't test since I don't have a tilt enabled tablet. >_<

**Comment by briend** [comment]
Well, not really an *alternative*, they are all really important, I think.  Here is a pencil I am working on.  So I am using Attack Angle to control jitter while the pencil is at an declinated slightly, so that strokes that are side-to-side are fuzzy and stroke that are forward and backward are less fuzzy.  When you draw a circle you can see it transition from fuzzy to tight, where the arrows are pointing.  But I'm also using Declination to further restrict the jitter so that when I stand the pen straight up it is a very fine point. There's also something totally cool that I just realized is possible tonight.  When you tilt the Art Pen a lot I start introducing smudge and allowing the jitter to come back.  BUT, here's the cool part.  Go a bit farther still and the pressure sensor stops working on the art pen (dumb design?), but that won't stop MyPaint!  We can just map declination to opacity and continue on where where pressure left off.  Now we're rubbing the wooden part of the pencil against the drawing and smudging it more, and we're finally tilting the pencil almost flat and some of the yellow paint is rubbing onto the drawing.  Pretty cool?  Oh, I'm using Ascension (bearing?) here to control the dab angle, so that when the ratio is stretched out they still align parallel with whatever bearing/ascension the stylus is pointing.  I've attached the brush as a txt file if anyone wants to try it (rename to .myb and place in brushes folder)

yellowpencil


yellow_wood_pencil_prev
[Yellow_Wood_Pencil.txt](https://github.com/mypaint/libmypaint/files/1096921/Yellow_Wood_Pencil.txt)

**Comment by briend** [comment]
Sorry you don't have a tilt tablet!  ;(

**Comment by achadwick** [comment]
@odysseywestra 
> Declination and Ascension(which should be renamed to vertical and horizontal tilt but I'll leave that for another issue)

The terminology is really, really confusing for sure, but it's not as simple as an x/y tilt pair.

They're terms from [astronomy](https://en.wikipedia.org/wiki/Equatorial_coordinate_system). I kid you not. We simplify it a bit, but this doesn't help people to understand it much!

> I'm still confused by how it all work(I'm a visual learner),

I get you. Loads of artists will be exactly like this and I want to improve *everything* about this and make it really slick.

Libmypaint exposes some translated names, which could be improved.

I'd love it if the MyPaint brush customization interface had some nice vector drawings of what the scarier-sounding brush dynamics mean. But that interface is exceptionally difficult to design for: there's so many levels of "choice and doing" hierarchy involved:

* Choice of brush
  * Actions on this brush (edit icon, save, copy to new, ...)
  * Choice of setting group (e.g. "Basic")    
    * Choice of a setting for this brush (e.g. Radius)
      * Explanation about what this setting produces.
      * This setting's base value
      * Choice of (dynamics) inputs (e.g. "[vary it by] Fine speed")
        * Explain where this input comes from
        * Nonlinear response graph (input points)
          * Bottom and top X axis values
    * Description and notes fields in the special "About" group.

That's six levels deep, although we auto-unfold some bits of it. But we have to reflect

**Comment by achadwick** [comment]
I can test bits of this - I have a couple of tilt-sensitive tablets in my collection now. I don't have an Art Pen or any stylus with a wheel on it though.

I want an examples brush group with a single, boring, round but useful, base brush, and lots of examples derived from it. Examples ought to do *one* thing each. The examples ought each to to demonstrate just the most obvious way you can customize some setting/output or input/dynamic. Ideally with carefully written notes ("this brush demonstrates how you can use tilt to control the angle of an elliptical blob, like a flat painting brush in the real world"...). People ought to be able to use those brushes as bases for their own brush collection, but that's less important than their teaching use ☺

**Comment by briend** [comment]
@achadwick Just to be clear, this patch and the brush sample don't need an Art Pen or Wheel at all.  Just tilt.

Attack Angle (or Angle of Attack, AOA) seems to follow the tradition of obscure terms, doesn't it?  "representing the relative motion between the body and the fluid through which it is moving." - Wikipedia.
Actually...  dang . . .   Angle of Sideslip (AOS) might be more accurate still: https://en.wikipedia.org/wiki/Slip_(aerodynamics)  "The sideslip angle β  is essentially the directional angle of attack of the airplane."

Which sounds cooler though, "attack" or "sideslip"? :-)  Ok, more seriously, is there a word that could be more understandable for this angle?

I really like the ideas about learning-by-example with a "tutorial brushpack" sort of thing.  One idea I had (https://github.com/mypaint/mypaint/issues/778) was highlighting the settings that a brush is using, specifically so you can load up a brush and figure out how it works more easily.

**Comment by odysseywestra** [comment]
Okay I was able to borrow n Wacom Pro Tablet from someone in my local LUG. He said it was just collecting dust and was glad it being put to good use. So I can now test these parameters out.

**Comment by briend** [comment]
Awesome!  For attack angle a "W" or "M" shape usually makes more sense.  If you move the peak to one side and control radius you can simulate an offset pen holder like this:
http://www.paperpenalia.com/flex2.html

**Comment by briend** [comment]
I'm closing this pull because I ended up merging it with anti_offsets to share the direction_360 code.  Direction_360, Offsets side+mirrored, and attack angle are all related.

https://github.com/mypaint/libmypaint/tree/anti_offset

**Pull request closed without merging**
