### PR TITLE
Brush Inputs: Direction360 + Attack Angle

### PR DESCRIPTION
**Pull request by briend**
This patch adds "Attack Angle" to the brush inputs-- which is the difference between the angle the stylus is pointing and the angle of its stroke movement on the canvas in degrees.  Here's a link to the [community thread ](https://community.mypaint.org/t/new-input-type-angle-of-attack/136)for more background. 

Attack Angle depends on Direction 360 (thanks @AnTi-ArT !!) so I think this is the right thing to do, but this is my first experience with git.  This also fixes an Ascension bug that I submitted as another pull (https://github.com/mypaint/libmypaint/pull/59).  Two examples, first modifying jitter to simulate a flattened pencil/tapered charcoal/conte crayon.  Second, replacing Pressure with Attack Angle to make Deevad's soft dip pen react more like a real dip pen (IMO).
screenshot from 2016-07-23 18-21-10
screenshot from 2016-07-23 19-25-36

### CODE REVIEW

**Comment by 0ion9** [comment]
After reading the commit, I see what you have done here (`created a setting 'Attack Angle` which represents "The difference between the angle the stylus is pointing and the angle of its stroke movement on the canvas (degrees)"`)

. For future reference, please include a clear, brief summary in the PR, giving a high-level overview of exactly what your commit(s) do. Preferably as the very first paragraph.

**Comment by briend** [comment]
Thanks @0ion9, I've updated the PR with some extra info and a link to the community thread.  I hope I did the right thing creating a new pull with @AnTi-ArT's  Direction 360 included.  I'm not exactly sure what I'm doing, obviously :-)

**Comment by briend** [comment]
Closing for now, I want to make some additional changes

**Comment by briend** [comment]
I'm going to change the input to map 0-180 with 90 degrees being movement to the right of the pointed direction, and -90 degrees being movement to the left of the pointed direction.   Right now I have 90 degrees meaning side-to-side movement regardless of left vs right-- but there is no reason not to have more information.

**Pull request closed without merging**
