### PR TITLE
Update es.po translations from 0.7.1 to 1.2.0 and add es_ES.po translation too

### PR DESCRIPTION
**Pull request by shakaran**
I just update the Spanish translations from 0.7.1 to 1.2.0 strings (I didn't use weblate, directly with poedit and doing the PR here)

### CODE REVIEW

**Comment by shakaran** [comment]
ping to @Jehan since he seems commiter here too

**Comment by Jehan** [comment]
Hi,

I would merge but I don't really know the process for translation on libmypaint.
Also I don't speak Spanish so I can't really validate your changes, only trust a contributor knows what one is doing.

@achadwick What's the process here?

**Comment by achadwick** [comment]
Okay, weblate is there to provide a nice frontend for translators, but it isn't auto-merged back yet (this should happen...)

The recommended method is to use weblate exclusively, otherwise edit branches may in fact be using outdated information.

First step is to pull changes from weblate onto master:

```
$ git remote -v
[...]
weblate	git://git.weblate.org/libmypaint.git (fetch)
weblate	git://git.weblate.org/libmypaint.git (push)
$ git pull
$ git pull weblate master
```

The affected files are already listed in po/LINGUAS, so that file doesn't need updating. **Normally** you would now do:

```
$ git push   # XXX not today!
```

and tell the contributor to merge and do a forced push.

But that's a bit rude, and I should be better at monitoring, so today I will do the merge and get weblate back into sync. We can use the PR thread to discuss the conflict. There is only one string in conflict.

**Comment by achadwick** [comment]
Whoops, didn't see es_ES.po. I've listed it.

Merged manually. Thanks @shakaran!

This may be enough, but please check it, especially the string highlighted. below.

@Jehan When you push onto master, weblate updates. That bit's automated, but not the reverse.

This is the string conflict I resolved:

```po
<<<<<<< HEAD
"Se multiplica por la opacidad. Sólo debería cambiar la entrada de presión "
"para este ajuste. Use 'opacidad' en cambio para hacer que la opacidad "
"dependa de la velocidad.\n"
"Este ajuste determina el que se detenga el pintado cuando hay presión cero. "
"Es sólo una convención, el comportamiento es idéntico a 'opacidad'."
=======
"Se multiplica con opaco. Sólo debe cambiar la presión de entrada de este "
"ajuste. En cambio, utilice \"opaco\" para que la opacidad dependa de la "
"velocidad.\n"
"Este ajuste es responsable de dejar de pintar cuando no hay presión. Es sólo "
"una convención, el comportamiento es idéntico a 'opaco'."
>>>>>>> cb031a7cb69e9e9acdb803b61843d6005ff4ea1e
```

The second translation is the one contributed by @shakaran. Thank you, I am using this text as the resolution ("no hay presión" is more understandable to me, and your contrib is newer), but can you confirm or let me know what you need it to say?

I note that the string being translated is sadly not very grammatical English. I should reword the part you see as

> [...] This setting is responsible for stopping painting when there is zero pressure. [...]

but that will have to wait until after the release.

**Comment by shakaran** [comment]
@achadwick thanks for the quick shipping and merge!

I generaly use word or tems more understandable in the translations, indeed there are words or messages not very gramatical, but I think that it would be understable for most of spanish people, if not we can always update again the translation for minor changes. The goal is make that the library will be used in a lot native apps which use spanish people and increase the popularity with open source in that tools.

The conflict I think that it is nice resolved, so I think that it is safe to release, if someone complains we always could realse a 1.2.1 minor with the translations updated

**Pull request merged**
