### PR TITLE
[RFC] Alternative symmetry modes

### PR DESCRIPTION
**Pull request by ShadowKyogre**
Implements #27 .

The reason why the [RFC] is in the pull request title is that I was working on getting this into a presentable, working state before asking for comments on the implementation.

The following commits implement horizontal, horizontal + vertical, rotational, and snowflake symmetry.

The only major gripe I have about the implementation is that the rotational symmetry lines is part of the function signature for the whole symmetry state instead of being treated as an exclusive field for angle dependent symmetry modes.

The other concern I have is that there IS an alternative snowflake symmetry mode that I came across while polishing my code, but it's not as intuitive as the current one. That alternative mode reflects across the symmetry lines from rotation.

I'm not sure if I should implement that since the snowflake mode is meant to mimic Krita's snowflake mode.

### CODE REVIEW

**Comment by odysseywestra** [comment]
Could you rebase this? I've been having trouble building this with mypaint/mypaint#720 and rebasing it seem to fix the problem I was having.

**Comment by ShadowKyogre** [comment]
Just finished rebasing it. Try rebuilding now.

**Comment by odysseywestra** [comment]
On Monday, I'm going to merge this PR into libmypaint master since it's passed all checks on our CI tools. Also this PR is needs to be merged first so the CI tools can test out the pull request on mypaint/mypaint#720. If anyone from @mypaint/developers need to address anything on the PR, now is the time.

After the merge is made, @ShadowKyogre , be prepared to make any fixes that any of our Contributors, and Users may report that is related to your commits. @achadwick could you add @ShadowKyogre to the @mypaint/developers team so that user can make fix any issues that may arise if need be without having to make another pull request?

**Comment by QuLogic** [comment]
This change breaks ABI, which means the soversion must be bumped.

**Comment by odysseywestra** [comment]
> This change breaks ABI, which means the soversion must be bumped.

The version is already set for a development cycle as of b7377e262a646c02700e174658d689647573ffa1, unless you're referring to something different.

**Comment by QuLogic** [comment]
The version is not the same as the soversion.

**Comment by odysseywestra** [comment]
Where do we update the soversion? Plus when do we have to update it? Sorry I'm asking all these questions, I'm still learning all of this.

**Comment by odysseywestra** [comment]
@QuLogic so all that @ShadowKyogre needs to do is to bump this number on this line to one?

https://github.com/mypaint/libmypaint/blob/b7377e262a646c02700e174658d689647573ffa1/configure.ac#L15

**Comment by QuLogic** [comment]
Well, all three actually, but libtool recommends doing this only at release time. I don't know what the convention is here, but if it's not done now, it should be noted down somewhere as something to be done before the release.

**Comment by odysseywestra** [comment]
I'll make sure to note in the project section of the repository to make sure to update the ABI before release. No need to worry about it now then. The reason is there is going to be a few merges that are going to add the functionality to libmypaint. Thank you for pointing that out.

If anyone from @mypaint/developers has anything that needs to be addressed with this pull request, please leave a comment here or on the line that needs to be addressed.

**Comment by odysseywestra** [comment]
Okay I'm going to merge this PR. @ShadowKyogre be ready for any bug reports that may arise for the brush library that are related to your PR.

**Pull request merged**
