### PR TITLE
Build cleanup

### PR DESCRIPTION
**Pull request by QuLogic**
Remove some unused checks and defines.

BTW, have you considered switching to [meson](http://mesonbuild.com/)?

### CODE REVIEW

**Comment by odysseywestra** [comment]
Could anyone else from @mypaint/developers review this to make sure those checks and defines unused?

**Comment by odysseywestra** [comment]
@blackwarthog, could you review this PR?

**Comment by blackwarthog** [comment]
I'm not a member of libmypaint developers team. I've explored libmypaint sources only one week to fix bug #83. Are you sure that will my review enough or helpful?

**Comment by martinxyz** [comment]
We seem to be waiting for someone to say "I can build on Windows/MacOS with this change". It doesn't matter if you're in the team or not.

@QuLogic You already seem to have the rights to merge this yourself. If you are even semi-confident I suggest you just merge and deal with the bugs later, if any pop up.

**Comment by QuLogic** [comment]
Oh, I suppose I do.

**Pull request merged**
